import LeanVerification

-- Generated by audit.py; no declarations are added.

-- CollectiveEnergy.lean
#print axioms IC.rotated_radius
#print axioms IC.pair_separation
#print axioms IC.pair_energy_from_cores
#print axioms IC.radial_jet_constraints
#print axioms IC.angular_jet
#print axioms IC.pair_jet_coefficients
#print axioms IC.energy_gradient_P
#print axioms IC.energy_gradient_T
#print axioms IC.mixed_derivative
#print axioms IC.apex_coefficients
#print axioms IC.apex_deviator_polynomial
#print axioms IC.neel_cancellation
#print axioms IC.even_core_pair

-- Dimensions.lean
#print axioms IC.coefficient_dimensions
#print axioms IC.gradient_dimensions

-- Exchange.lean
#print axioms IC.thin_shell_energy
#print axioms IC.covariant_square
#print axioms IC.moving_frame_exchange
#print axioms IC.tangential_energy
#print axioms IC.anisotropy_difference
#print axioms IC.interface_extrinsic
#print axioms IC.bulk_extrinsic
#print axioms IC.bulk_principal

-- GaussianProfile.lean
#print axioms IC.profile_derivative
#print axioms IC.profile_second_derivative
#print axioms IC.metric_positive
#print axioms IC.graph_frame
#print axioms IC.azimuthal_extension
#print axioms IC.gaussian_curvature_product
#print axioms IC.exponential_square
#print axioms IC.apex_curvatures
#print axioms IC.deviation_formula
#print axioms IC.deviation_nonnegative
#print axioms IC.gaussian_sign
#print axioms IC.gaussian_curvature_sign
#print axioms IC.gaussian_ring
#print axioms IC.profile_odd
#print axioms IC.metric_even
#print axioms IC.curvatures_odd
#print axioms IC.curvature_jet
#print axioms IC.local_derivative_relation
#print axioms IC.projected_axis_parity
#print axioms IC.scale_ratio
#print axioms IC.curvature_denominator

-- Geometry.lean
#print axioms IC.gram_identity
#print axioms IC.normalized_normal
#print axioms IC.recover_principal
#print axioms IC.mean_sq_sub_dev_sq
#print axioms IC.normal_reversal
#print axioms IC.magnitude_criterion
#print axioms IC.offset_area
#print axioms IC.upper_face
#print axioms IC.lower_face
#print axioms IC.connection_skew
#print axioms IC.moving_product

-- Intrinsic.lean
#print axioms IC.potential_monotone_slope
#print axioms IC.potential_even
#print axioms IC.poisson_final_step
#print axioms IC.slope_positive_curvature_negative

-- Magnetostatics.lean
#print axioms IC.volume_charge
#print axioms IC.face_volume_cancellation
#print axioms IC.thickness_primitive
#print axioms IC.thickness_polynomial_integral
#print axioms IC.thickness_integral
#print axioms IC.cross_prefactor
#print axioms IC.normal_kernel_derivative
#print axioms IC.kernel_decomposition
#print axioms IC.axial_harmonic_consequence
#print axioms IC.cutoff_ratio
#print axioms IC.quarter_factor
#print axioms IC.logarithmic_increment

-- Micromagnetics.lean
#print axioms IC.heisenberg_difference
#print axioms IC.magnetization_norm
#print axioms IC.energy_additivity
#print axioms IC.easy_axis_bound
#print axioms IC.easy_plane_nonnegative
#print axioms IC.zeeman_reversal
#print axioms IC.dipolar_energy_identity
#print axioms IC.bulk_dmi_reversal
#print axioms IC.interface_dmi_reversal
#print axioms IC.exchange_length_balance
#print axioms IC.anisotropy_length_balance
#print axioms IC.dmi_length_balance
#print axioms IC.parallel_field_zero_torque

-- Orientation.lean
#print axioms IC.fixed_background_phases
#print axioms IC.central_derivative
#print axioms IC.central_second_derivative
#print axioms IC.phase_chain_second
#print axioms IC.mixed_X_orientation
#print axioms IC.mixed_Y_orientation
#print axioms IC.neel_orientation
#print axioms IC.bloch_orientation
#print axioms IC.angular_response

-- Selection.lean
#print axioms IC.mean_linearity
#print axioms IC.mean_zero
#print axioms IC.mean_two
#print axioms IC.mean_neg_two
#print axioms IC.axial_contraction
#print axioms IC.principal_harmonics
#print axioms IC.harmonic_arguments
#print axioms IC.selection_positive
#print axioms IC.selection_negative
#print axioms IC.passive_invariance
#print axioms IC.pair_angle
#print axioms IC.radial_integrand_reversal
#print axioms IC.core_energy_polarity
#print axioms IC.bloch_positive_zero
#print axioms IC.principal_swap
#print axioms IC.radial_double_angle

-- Stability.lean
#print axioms IC.hessian_completion
#print axioms IC.positive_definite_iff
#print axioms IC.schur_completion
#print axioms IC.relaxed_le_frozen
#print axioms IC.internal_inverse
#print axioms IC.harmonic_elimination
#print axioms IC.perturbative_order
#print axioms IC.eliminated_second_derivative
#print axioms IC.confined_determinant

-- Symmetry.lean
#print axioms IC.pair_height_reversal
#print axioms IC.coefficient_reversal
#print axioms IC.polarity_phase_reversal
#print axioms IC.energy_reversal
#print axioms IC.charge_reversal
#print axioms IC.reflection_polynomial
#print axioms IC.reflection_bulk
#print axioms IC.reflection_interface
#print axioms IC.reflection_charge
#print axioms IC.reflection_forbidden
#print axioms IC.reversed_path_barrier
#print axioms IC.minimum_becomes_maximum

-- Topology.lean
#print axioms IC.topological_density_reversal
#print axioms IC.axial_unit
#print axioms IC.axial_density
#print axioms IC.radial_primitive
#print axioms IC.radial_charge
#print axioms IC.skyrmion_charge
#print axioms IC.meron_charge
#print axioms IC.bimeron_charge
#print axioms IC.equal_polarities
#print axioms IC.rotation_norm
#print axioms IC.rotation_triple
#print axioms IC.bp_unit
#print axioms IC.bp_core_positive
#print axioms IC.bp_core_negative
#print axioms IC.exchange_scaling
